# Fortune 100 (2025/26 ranking per us500.com) -> Workday tenant candidates
# Each entry: rank, name, [candidate tenant slugs]
FORTUNE100 = [
 (1,"Amazon",["amazon"]),
 (2,"Walmart",["walmart"]),
 (3,"UnitedHealth Group",["unitedhealthgroup","uhg","optum"]),
 (4,"Apple",["apple"]),
 (5,"Alphabet (Google)",["google","alphabet"]),
 (6,"CVS Health",["cvshealth"]),
 (7,"Berkshire Hathaway",["berkshirehathaway"]),
 (8,"McKesson",["mckesson"]),
 (9,"Exxon Mobil",["exxonmobil"]),
 (10,"Cencora",["cencora","amerisourcebergen"]),
 (11,"Microsoft",["microsoft"]),
 (12,"JPMorgan Chase",["jpmorganchase","jpmc"]),
 (13,"Costco Wholesale",["costco"]),
 (14,"Cigna Group",["cigna","evernorth"]),
 (15,"Cardinal Health",["cardinalhealth"]),
 (16,"Nvidia",["nvidia"]),
 (17,"Meta Platforms",["meta","facebook"]),
 (18,"Elevance Health",["elevancehealth","antheminc","elevance"]),
 (19,"Centene",["centene"]),
 (20,"Bank of America",["bankofamerica","bofa"]),
 (21,"Chevron",["chevron"]),
 (22,"Ford Motor",["ford"]),
 (23,"General Motors",["generalmotors","gm"]),
 (24,"Citigroup",["citi","citigroup"]),
 (25,"Home Depot",["homedepot"]),
 (26,"Fannie Mae",["fanniemae"]),
 (27,"Kroger",["kroger"]),
 (28,"Verizon Communications",["verizon"]),
 (29,"Phillips 66",["phillips66"]),
 (30,"Marathon Petroleum",["marathonpetroleum","mpc"]),
 (31,"StoneX Group",["stonex"]),
 (32,"State Farm Insurance",["statefarm"]),
 (33,"Freddie Mac",["freddiemac"]),
 (34,"Humana",["humana"]),
 (35,"AT&T",["att"]),
 (36,"Goldman Sachs Group",["goldmansachs","gs"]),
 (37,"Comcast",["comcast"]),
 (38,"Wells Fargo",["wellsfargo","wf"]),
 (39,"Morgan Stanley",["morganstanley","ms"]),
 (40,"Valero Energy",["valero"]),
 (41,"Dell Technologies",["dell"]),
 (42,"Target",["target"]),
 (43,"Tesla",["tesla"]),
 (44,"Walt Disney",["disney"]),
 (45,"Johnson & Johnson",["jnj","johnsonandjohnson"]),
 (46,"PepsiCo",["pepsico"]),
 (47,"Boeing",["boeing"]),
 (48,"UPS",["ups"]),
 (49,"RTX",["rtx","raytheon"]),
 (50,"FedEx",["fedex"]),
 (51,"Progressive",["progressive"]),
 (52,"Lowe's",["lowes"]),
 (53,"Energy Transfer",["energytransfer"]),
 (54,"Procter & Gamble",["pg","procterandgamble"]),
 (55,"Sysco",["sysco"]),
 (56,"American Express",["aexp","americanexpress"]),
 (57,"Albertsons",["albertsons"]),
 (58,"Archer Daniels Midland",["adm"]),
 (59,"MetLife",["metlife"]),
 (60,"HCA Healthcare",["hca","hcahealthcare"]),
 (61,"Lockheed Martin",["lockheedmartin","lmco"]),
 (62,"New York Life Insurance",["newyorklife","nyl"]),
 (63,"Capital One Financial",["capitalone"]),
 (64,"Allstate",["allstate"]),
 (65,"Caterpillar",["caterpillar","cat"]),
 (66,"IBM",["ibm"]),
 (67,"Eli Lilly",["lilly","elililly"]),
 (68,"Merck",["merck","msd"]),
 (69,"Nationwide",["nationwide"]),
 (70,"Broadcom",["broadcom"]),
 (71,"Delta Air Lines",["delta","deltaairlines"]),
 (72,"Publix Super Markets",["publix"]),
 (73,"Pfizer",["pfizer"]),
 (74,"TD Synnex",["tdsynnex","synnex"]),
 (75,"ConocoPhillips",["conocophillips"]),
 (76,"Galaxy Digital",["galaxydigital"]),
 (77,"AbbVie",["abbvie"]),
 (78,"Prudential Financial",["prudential"]),
 (79,"TJX",["tjx"]),
 (80,"Performance Food Group",["performancefoodgroup","pfgc"]),
 (81,"United Airlines Holdings",["united","unitedairlines"]),
 (82,"Oracle",["oracle"]),
 (83,"Cisco Systems",["cisco"]),
 (84,"HP",["hp"]),
 (85,"Charter Communications",["charter","spectrum"]),
 (86,"American Airlines Group",["aa","americanairlines"]),
 (87,"Tyson Foods",["tyson","tysonfoods"]),
 (88,"Intel",["intel"]),
 (89,"Enterprise Products Partners",["enterpriseproducts","eprod"]),
 (90,"Ingram Micro Holding",["ingrammicro"]),
 (91,"General Dynamics",["generaldynamics","gd"]),
 (92,"Uber Technologies",["uber"]),
 (93,"USAA",["usaa"]),
 (94,"TIAA",["tiaa"]),
 (95,"Liberty Mutual Insurance Group",["libertymutual"]),
 (96,"Travelers",["travelers"]),
 (97,"Bristol-Myers Squibb",["bms","bristolmyerssquibb"]),
 (98,"Coca-Cola",["coca-cola","cocacola"]),
 (99,"Nike",["nike"]),
 (100,"Massachusetts Mutual Life",["massmutual"]),
]

# Confirmed-good Workday endpoints (tenant, wd_host, site)
CONFIRMED = {
 "Nvidia": ("nvidia","wd5","NVIDIAExternalCareerSite"),
 "CVS Health": ("cvshealth","wd1","CVS_Health_Careers"),
 "Target": ("target","wd5","targetcareers"),
 "Dell Technologies": ("dell","wd1","External"),
 "HP": ("hp","wd5","ExternalCareerSite"),
 "Intel": ("intel","wd1","External"),
 "Pfizer": ("pfizer","wd1","PfizerCareers"),
 "Comcast": ("comcast","wd5","Comcast_Careers"),
 "Citigroup": ("citi","wd5","2"),
}

# Common Workday site-slug patterns to brute force
SITE_CANDIDATES = [
 "External","external","careers","Careers","ExternalCareerSite","External_Career_Site",
 "CareerSite","Career_Site","ExternalSite","Externals","JobSearch","jobs","Jobs",
 "{t}careers","{t}Careers","{t}_Careers","{t}_careers","{t}-careers","{t}External",
 "{t}_External","{t}externalcareers","{t}ExternalCareerSite","Global","GlobalCareers",
 "US_External_Career_Site","External_Careers","ExternalCareers","1","2","3",
]
WD_HOSTS = ["wd1","wd5","wd3","wd2","wd12","wd103","wd101"]
