# company -> (tenant, wd_host, site)  [verified via search + API probe]
ENDPOINTS = {
 "Walmart": ("walmart","wd5","WalmartExternal"),
 "UnitedHealth Group": None,
 "Apple": None,
 "Amazon": None,
 "Alphabet (Google)": None,
 "CVS Health": ("cvshealth","wd1","CVS_Health_Careers"),
 "Berkshire Hathaway": None,
 "McKesson": ("mckesson","wd3","External_Careers"),
 "Exxon Mobil": None,
 "Cencora": ("myhrabc","wd5","Global"),
 "Microsoft": None,
 "JPMorgan Chase": None,
 "Costco Wholesale": None,
 "Cigna Group": ("cigna","wd5","cignacareers"),
 "Cardinal Health": ("cardinalhealth","wd1","EXT"),
 "Nvidia": ("nvidia","wd5","NVIDIAExternalCareerSite"),
 "Meta Platforms": None,
 "Elevance Health": ("elevancehealth","wd1","ANT"),
 "Centene": ("centene","wd5","Centene_External"),
 "Bank of America": None,
 "Chevron": ("chevron","wd5","jobs"),
 "Ford Motor": None,
 "General Motors": ("generalmotors","wd5","Careers_GM"),
 "Citigroup": ("citi","wd5","2"),
 "Home Depot": ("homedepot","wd5","CareerDepot"),
 "Fannie Mae": ("fanniemae","wd1","FannieMaeCareers"),
 "Kroger": None,
 "Verizon Communications": ("verizon","wd5","verizon-careers"),
 "Phillips 66": None,
 "Marathon Petroleum": ("mpc","wd1","MPCCareers"),
 "StoneX Group": None,
 "State Farm Insurance": None,
 "Freddie Mac": ("freddiemac","wd5","External"),
 "Humana": ("humana","wd5","Humana_External_Career_Site"),
 "AT&T": None,
 "Goldman Sachs Group": None,
 "Comcast": ("comcast","wd5","Comcast_Careers"),
 "Wells Fargo": ("wf","wd1","WellsFargoJobs"),
 "Morgan Stanley": ("ms","wd5","External"),
 "Valero Energy": None,
 "Dell Technologies": ("dell","wd1","External"),
 "Target": ("target","wd5","targetcareers"),
 "Tesla": None,
 "Walt Disney": ("disney","wd5","disneycareer"),
 "Johnson & Johnson": ("jj","wd5","JJ"),
 "PepsiCo": None,
 "Boeing": ("boeing","wd1","EXTERNAL_CAREERS"),
 "UPS": ("hcmportal","wd5","Search"),
 "RTX": ("globalhr","wd5","REC_RTX_Ext_Gateway"),
 "FedEx": ("fedex","wd1","FDW_External_Career_Site"),
 "Progressive": None,
 "Lowe's": ("lowes","wd5","LWS_External_CS"),
 "Energy Transfer": None,
 "Procter & Gamble": ("pg","wd5","1000"),
 "Sysco": ("sysco","wd5","syscocareers"),
 "American Express": None,
 "Albertsons": None,
 "Archer Daniels Midland": None,
 "MetLife": None,
 "HCA Healthcare": ("hcahealthcare","wd3","hcacareers"),
 "Lockheed Martin": None,
 "New York Life Insurance": None,
 "Capital One Financial": ("capitalone","wd12","Capital_One"),
 "Allstate": ("allstate","wd5","allstate_careers"),
 "Caterpillar": ("cat","wd5","CaterpillarCareers"),
 "IBM": None,
 "Eli Lilly": ("lilly","wd5","LLY"),
 "Merck": ("msd","wd5","SearchJobs"),
 "Nationwide": ("nationwide","wd1","Nationwide_Career"),
 "Broadcom": ("broadcom","wd1","External_Career"),
 "Delta Air Lines": None,
 "Publix Super Markets": None,
 "Pfizer": ("pfizer","wd1","PfizerCareers"),
 "TD Synnex": None,
 "ConocoPhillips": ("conocophillips","wd1","External"),
 "Galaxy Digital": None,
 "AbbVie": None,
 "Prudential Financial": ("pru","wd5","Careers"),
 "TJX": ("tjx","wd1","TJX_EXTERNAL"),
 "Performance Food Group": None,
 "United Airlines Holdings": None,
 "Oracle": None,
 "Cisco Systems": ("cisco","wd5","Cisco_Careers"),
 "HP": ("hp","wd5","ExternalCareerSite"),
 "Charter Communications": None,
 "American Airlines Group": None,
 "Tyson Foods": ("tysonfoods","wd5","TSN"),
 "Intel": ("intel","wd1","External"),
 "Enterprise Products Partners": None,
 "Ingram Micro Holding": None,
 "General Dynamics": ("gdit","wd5","External_Career_Site"),
 "Uber Technologies": None,
 "USAA": ("usaa","wd1","USAAJOBSWD"),
 "TIAA": ("tiaa","wd1","Search"),
 "Liberty Mutual Insurance Group": None,
 "Travelers": ("travelers","wd5","External"),
 "Bristol-Myers Squibb": ("bristolmyerssquibb","wd5","BMS"),
 "Coca-Cola": ("coke","wd1","coca-cola-careers"),
 "Nike": ("nike","wd1","nke"),
 "Massachusetts Mutual Life": ("massmutual","wd1","MMAscendCareers"),
}

# Careers URLs for companies with no machine-readable API (manual-check column)
CAREERS_URL = {
 "UnitedHealth Group":"https://careers.unitedhealthgroup.com/",
 "Apple":"https://jobs.apple.com/en-us/search",
 "Amazon":"https://www.amazon.jobs/en/",
 "Alphabet (Google)":"https://www.google.com/about/careers/applications/jobs/results/",
 "Berkshire Hathaway":"https://www.berkshirehathaway.com/careers/careers.html",
 "Exxon Mobil":"https://jobs.exxonmobil.com/",
 "Microsoft":"https://jobs.careers.microsoft.com/global/en/search",
 "JPMorgan Chase":"https://careers.jpmorgan.com/us/en/home",
 "Costco Wholesale":"https://www.costco.com/careers.html",
 "Meta Platforms":"https://www.metacareers.com/jobs",
 "Bank of America":"https://careers.bankofamerica.com/en-us/job-search",
 "Ford Motor":"https://careers.ford.com/",
 "Kroger":"https://www.thekrogerco.com/careers/",
 "Phillips 66":"https://jobs.phillips66.com/",
 "StoneX Group":"https://www.stonex.com/en/careers/",
 "State Farm Insurance":"https://www.statefarm.com/careers",
 "AT&T":"https://www.att.jobs/",
 "Goldman Sachs Group":"https://higher.gs.com/roles",
 "Valero Energy":"https://www.valero.com/careers",
 "Tesla":"https://www.tesla.com/careers/search/",
 "PepsiCo":"https://www.pepsicojobs.com/",
 "Progressive":"https://careers.progressive.com/",
 "Energy Transfer":"https://www.energytransfer.com/careers/",
 "American Express":"https://aexp.eightfold.ai/careers",
 "Albertsons":"https://www.albertsonscompanies.com/careers/",
 "Archer Daniels Midland":"https://careers.adm.com/",
 "MetLife":"https://careers.metlife.com/",
 "Lockheed Martin":"https://www.lockheedmartinjobs.com/",
 "New York Life Insurance":"https://www.newyorklife.com/careers",
 "IBM":"https://www.ibm.com/careers/search",
 "Delta Air Lines":"https://careers.delta.com/",
 "Publix Super Markets":"https://corporate.publix.com/careers",
 "TD Synnex":"https://careers.tdsynnex.com/",
 "Galaxy Digital":"https://www.galaxy.com/careers/",
 "AbbVie":"https://careers.abbvie.com/en",
 "Performance Food Group":"https://www.pfgc.com/Careers",
 "United Airlines Holdings":"https://careers.united.com/",
 "Oracle":"https://careers.oracle.com/jobs",
 "Charter Communications":"https://jobs.spectrum.com/",
 "American Airlines Group":"https://jobs.aa.com/",
 "Enterprise Products Partners":"https://www.enterpriseproducts.com/careers",
 "Ingram Micro Holding":"https://jobs.ingrammicro.com/",
 "Uber Technologies":"https://www.uber.com/us/en/careers/list/",
 "Liberty Mutual Insurance Group":"https://jobs.libertymutualgroup.com/",
}
