# Fortune 101-200 (us500.com ranking) -> (workday tenant candidates, careers URLs to fingerprint)
F200 = [
 (101,"GE Aerospace",["geaerospace","ge"],["https://jobs.geaerospace.com/","https://www.geaerospace.com/careers"]),
 (102,"Deere",["deere","johndeere"],["https://careers.deere.com/"]),
 (103,"Plains GP Holdings",["plains","paalp"],["https://www.plains.com/careers"]),
 (104,"Molina Healthcare",["molinahealthcare","molina"],["https://careers.molinahealthcare.com/"]),
 (105,"Netflix",["netflix"],["https://explore.jobs.netflix.net/careers"]),
 (106,"Thermo Fisher Scientific",["thermofisher","tmo"],["https://jobs.thermofisher.com/"]),
 (107,"Abbott Laboratories",["abbott"],["https://www.jobs.abbott/"]),
 (108,"Qualcomm",["qualcomm"],["https://careers.qualcomm.com/"]),
 (109,"Northwestern Mutual",["northwesternmutual","nm"],["https://careers.northwesternmutual.com/"]),
 (110,"U.S. Bancorp",["usbank","usbancorp"],["https://careers.usbank.com/"]),
 (111,"Dollar General",["dollargeneral"],["https://careers.dollargeneral.com/"]),
 (112,"Northrop Grumman",["ngc","northropgrumman"],["https://www.northropgrumman.com/careers"]),
 (113,"Best Buy",["bestbuy"],["https://jobs.bestbuy.com/"]),
 (114,"Salesforce",["salesforce"],["https://careers.salesforce.com/en/jobs/"]),
 (115,"Bank of New York (BNY)",["bny","bnymellon"],["https://jobs.bny.com/"]),
 (116,"Honeywell International",["honeywell"],["https://careers.honeywell.com/us/en"]),
 (117,"Philip Morris International",["pmi","philipmorris"],["https://www.pmi.com/careers"]),
 (118,"CBRE Group",["cbre"],["https://careers.cbre.com/"]),
 (119,"Visa",["visa"],["https://corporate.visa.com/en/jobs/"]),
 (120,"Dow",["dow"],["https://corporate.dow.com/en-us/careers.html"]),
 (121,"US Foods Holding",["usfoods"],["https://careers.usfoods.com/"]),
 (122,"Mondelez International",["mdlz","mondelez"],["https://www.mondelezinternational.com/careers/"]),
 (123,"Lithia Motors",["lithia"],["https://careers.lithiadriveway.com/"]),
 (124,"GE Vernova",["gevernova"],["https://jobs.gevernova.com/"]),
 (125,"Micron Technology",["micron"],["https://careers.micron.com/"]),
 (126,"Warner Bros. Discovery",["wbd","warnerbros"],["https://careers.wbd.com/"]),
 (127,"Starbucks",["starbucks"],["https://careers.starbucks.com/"]),
 (128,"World Kinect",["worldkinect","wfscorp"],["https://www.worldkinect.com/careers"]),
 (129,"Amgen",["amgen"],["https://careers.amgen.com/"]),
 (130,"CHS",["chsinc","chs"],["https://careers.chsinc.com/"]),
 (131,"Advanced Micro Devices",["amd"],["https://careers.amd.com/"]),
 (132,"Coupang",["coupang"],["https://www.coupang.jobs/en/"]),
 (133,"Hewlett Packard Enterprise",["hpe"],["https://careers.hpe.com/"]),
 (134,"D.R. Horton",["drhorton"],["https://careers.drhorton.com/"]),
 (135,"Lennar",["lennar"],["https://careers.lennar.com/"]),
 (136,"PNC Financial Services Group",["pnc"],["https://careers.pnc.com/"]),
 (137,"Cummins",["cummins"],["https://careers.cummins.com/"]),
 (138,"Oneok",["oneok"],["https://careers.oneok.com/"]),
 (139,"PayPal Holdings",["paypal"],["https://careers.pypl.com/"]),
 (140,"GuideWell Mutual Holding",["guidewell","floridablue"],["https://careers.guidewell.com/"]),
 (141,"Mastercard",["mastercard"],["https://careers.mastercard.com/"]),
 (142,"Nucor",["nucor"],["https://careers.nucor.com/"]),
 (143,"Apollo Global Management",["apollo"],["https://www.apollo.com/careers"]),
 (144,"Penske Automotive Group",["penske","penskeautomotive"],["https://www.penskecars.com/careers"]),
 (145,"Duke Energy",["dukeenergy","duke"],["https://www.duke-energy.com/careers"]),
 (146,"United Natural Foods",["unfi"],["https://careers.unfi.com/"]),
 (147,"Ferguson Enterprises",["ferguson"],["https://www.ferguson.com/careers"]),
 (148,"Arrow Electronics",["arrow"],["https://careers.arrow.com/"]),
 (149,"NRG Energy",["nrg"],["https://www.nrg.com/careers.html"]),
 (150,"Truist Financial",["truist"],["https://careers.truist.com/"]),
 (151,"Jabil",["jabil"],["https://jobs.jabil.com/"]),
 (152,"Southern",["southernco","southern"],["https://careers.southerncompany.com/"]),
 (153,"Gilead Sciences",["gilead"],["https://gilead.wd1.myworkdayjobs.com/gileadcareers","https://www.gilead.com/careers"]),
 (154,"PBF Energy",["pbfenergy"],["https://careers.pbfenergy.com/"]),
 (155,"Paramount Skydance",["paramount","viacomcbs"],["https://www.paramount.com/careers"]),
 (156,"KKR",["kkr"],["https://www.kkr.com/careers"]),
 (157,"Quanta Services",["quanta","quantaservices"],["https://careers.quantaservices.com/"]),
 (158,"Paccar",["paccar"],["https://www.paccar.com/careers/"]),
 (159,"Medline",["medline"],["https://jobs.medline.com/"]),
 (160,"Applied Materials",["appliedmaterials","amat"],["https://careers.appliedmaterials.com/"]),
 (161,"Hartford Insurance Group",["thehartford","hartford"],["https://www.thehartford.com/careers"]),
 (162,"CarMax",["carmax"],["https://careers.carmax.com/"]),
 (163,"Southwest Airlines",["southwest","swa"],["https://careers.southwestair.com/"]),
 (164,"Baker Hughes",["bakerhughes"],["https://careers.bakerhughes.com/"]),
 (165,"Charles Schwab",["schwab","charlesschwab"],["https://www.schwabjobs.com/"]),
 (166,"AutoNation",["autonation"],["https://careers.autonation.com/"]),
 (167,"NextEra Energy",["nexteraenergy","nextera"],["https://www.nexteraenergy.com/careers.html"]),
 (168,"Marsh & McLennan",["mmc","marshmclennan"],["https://careers.marshmclennan.com/"]),
 (169,"Booking Holdings",["bookingholdings","booking"],["https://careers.booking.com/"]),
 (170,"McDonald's",["mcdonalds"],["https://careers.mcdonalds.com/"]),
 (171,"HF Sinclair",["hfsinclair","hollyfrontier"],["https://careers.hfsinclair.com/"]),
 (172,"AIG",["aig"],["https://www.aig.com/careers"]),
 (173,"Occidental Petroleum",["oxy","occidental"],["https://oxy.wd5.myworkdayjobs.com/Corporate","https://www.oxy.com/careers/"]),
 (174,"Marriott International",["marriott"],["https://careers.marriott.com/"]),
 (175,"Jones Lang LaSalle",["jll"],["https://jll.wd1.myworkdayjobs.com/jllcareers","https://www.jll.com/en-us/careers"]),
 (176,"International Paper",["internationalpaper","ipaper"],["https://www.internationalpaper.com/careers"]),
 (177,"Freeport-McMoRan",["fcx","freeport"],["https://jobs.fcx.com/"]),
 (178,"Constellation Energy",["constellation","constellationenergy"],["https://jobs.constellationenergy.com/"]),
 (179,"Waste Management",["wm","wastemanagement"],["https://careers.wm.com/"]),
 (180,"Live Nation Entertainment",["livenation"],["https://www.livenationentertainment.com/careers/"]),
 (181,"Stryker",["stryker"],["https://careers.stryker.com/"]),
 (182,"Dollar Tree",["dollartree"],["https://dollartree.wd5.myworkdayjobs.com/dollartreeus","https://www.dollartreeinfo.com/careers"]),
 (183,"3M",["3m","mmm"],["https://3m.wd1.myworkdayjobs.com/Search","https://www.3m.com/3M/en_US/careers-us/"]),
 (184,"Kraft Heinz",["kraftheinz"],["https://careers.kraftheinz.com/"]),
 (185,"PG&E",["pge","pgecorp"],["https://www.pge.com/en/about/careers.html"]),
 (186,"Danaher",["danaher"],["https://jobs.danaher.com/"]),
 (187,"Union Pacific",["unionpacific","up"],["https://up.jobs/"]),
 (188,"Genuine Parts",["genuineparts","gpc"],["https://jobs.genpt.com/"]),
 (189,"Exelon",["exelon"],["https://jobs.exeloncorp.com/"]),
 (190,"BlackRock",["blackrock"],["https://careers.blackrock.com/"]),
 (191,"Block",["block","squareup"],["https://block.xyz/careers/jobs"]),
 (192,"Adobe",["adobe"],["https://careers.adobe.com/us/en"]),
 (193,"Reinsurance Group of America",["rgare","rga"],["https://careers.rgare.com/"]),
 (194,"Sherwin-Williams",["sherwin","sherwinwilliams"],["https://careers.sherwin-williams.com/"]),
 (195,"WESCO International",["wesco"],["https://careers.wesco.com/"]),
 (196,"Lear",["lear"],["https://www.lear.com/careers"]),
 (197,"Synchrony Financial",["synchronyfinancial","synchrony"],["https://synchronyfinancial.wd5.myworkdayjobs.com/careers","https://www.synchronycareers.com/"]),
 (198,"Amphenol",["amphenol"],["https://www.amphenol.com/careers"]),
 (199,"Ross Stores",["rossstores","ross"],["https://jobs.rossstores.com/"]),
 (200,"Newmont",["newmont"],["https://jobs.newmont.com/"]),
]

# real-world Workday site slugs observed across Fortune 100 discovery
SLUGS = ["External","external","Careers","careers","External_Careers","ExternalCareerSite",
 "External_Career_Site","EXTERNAL_CAREERS","ExternalCareers","EXT","Search","jobs","Global",
 "GlobalCareers","{t}careers","{t}Careers","{t}_Careers","{t}_careers","{t}-careers","{t}External",
 "{t}_External","{t}ExternalCareerSite","{t}jobs","{t}_jobs","{t}Jobs","CareerSite","Career_Site",
 "US_External_Career_Site","1","2","1000","corporate","Corporate"]
WD_HOSTS = ["wd1","wd5","wd3","wd12","wd2","wd103","wd101","wd503","wd505","wd108"]
