# Fortune 201-300 (demandsage 2026 listing; cross-checked for zero overlap with ranks 1-200)
F300 = [
 (201,"EOG Resources",["eogresources","eog"],["https://eogresources.wd1.myworkdayjobs.com/EOG","https://www.eogresources.com/careers/"]),
 (202,"State Street",["statestreet"],["https://careers.statestreet.com/"]),
 (203,"Macy's",["macys"],["https://www.macysjobs.com/"]),
 (204,"Group 1 Automotive",["group1auto","group1"],["https://careers.group1auto.com/"]),
 (205,"CDW",["cdw"],["https://cdw.wd5.myworkdayjobs.com/Careers","https://www.cdw.com/content/cdw/en/careers.html"]),
 (206,"Avnet",["avnet"],["https://avnet.wd1.myworkdayjobs.com/External","https://careers.avnet.com/"]),
 (207,"Halliburton",["halliburton"],["https://jobs.halliburton.com/"]),
 (208,"Super Micro Computer",["supermicro","smci"],["https://www.supermicro.com/en/careers"]),
 (209,"American Electric Power",["aep","aepcareers"],["https://careers.aep.com/"]),
 (210,"L3Harris Technologies",["l3harris","harris"],["https://careers.l3harris.com/"]),
 (211,"Becton Dickinson",["bd","bectondickinson"],["https://jobs.bd.com/"]),
 (212,"Carrier Global",["carrier"],["https://carrier.wd5.myworkdayjobs.com/jobs","https://jobs.carrier.com/"]),
 (213,"BJ's Wholesale Club",["bjs"],["https://careers.bjs.com/"]),
 (214,"Tenet Healthcare",["tenethealth","tenet"],["https://careers.tenethealth.com/"]),
 (215,"Fiserv",["fiserv"],["https://careers.fiserv.com/"]),
 (216,"Cognizant Technology Solutions",["cognizant"],["https://careers.cognizant.com/global/en"]),
 (217,"GE HealthCare Technologies",["gehc","gehealthcare"],["https://gehc.wd5.myworkdayjobs.com/GEHC_ExternalSite","https://jobs.gehealthcare.com/"]),
 (218,"Automatic Data Processing",["adp"],["https://jobs.adp.com/"]),
 (219,"Colgate-Palmolive",["colgate","colgatepalmolive"],["https://jobs.colgate.com/"]),
 (220,"Carvana",["carvana"],["https://www.carvana.com/careers"]),
 (221,"Altria Group",["altria"],["https://www.altria.com/careers"]),
 (222,"Boston Scientific",["bostonscientific","bsci"],["https://jobs.bostonscientific.com/"]),
 (223,"Cheniere Energy",["cheniere"],["https://careers.cheniere.com/"]),
 (224,"Parker-Hannifin",["parker","parkerhannifin"],["https://careers.parker.com/"]),
 (225,"Kimberly-Clark",["kimberlyclark","kcc"],["https://kimberlyclark.wd5.myworkdayjobs.com/Kimberly_Clark","https://www.careersatkc.com/"]),
 (226,"American Family Insurance Group",["amfam","americanfamily"],["https://amfam.wd1.myworkdayjobs.com/External","https://amfam.jobs/"]),
 (227,"General Mills",["generalmills"],["https://careers.generalmills.com/"]),
 (228,"Edison International",["edisonintl","sce"],["https://www.edisoncareers.com/"]),
 (229,"AutoZone",["autozone"],["https://careers.autozone.com/"]),
 (230,"Ameriprise Financial",["ameriprise"],["https://ameriprise.wd5.myworkdayjobs.com/External","https://www.ameriprise.com/careers"]),
 (231,"Intuit",["intuit"],["https://jobs.intuit.com/"]),
 (232,"Guardian Life",["guardianlife"],["https://guardianlife.wd5.myworkdayjobs.com/Guardian-Life-Careers"]),
 (233,"Cleveland-Cliffs",["clevelandcliffs","clf"],["https://www.clevelandcliffs.com/careers"]),
 (234,"Global Partners",["globalpartners","glp"],["https://www.globalp.com/careers/"]),
 (235,"Aramark",["aramark"],["https://careers.aramark.com/"]),
 (236,"Corebridge Financial",["corebridge"],["https://careers.corebridgefinancial.com/"]),
 (237,"Loews",["loews","loewscorp"],["https://loewscorp.wd1.myworkdayjobs.com/loewscorp"]),
 (238,"Lam Research",["lamresearch","lam"],["https://careers.lamresearch.com/"]),
 (239,"Goodyear Tire & Rubber",["goodyear"],["https://corporate.goodyear.com/us/en/careers.html"]),
 (240,"Pacific Life",["pacificlife"],["https://pacificlife.wd1.myworkdayjobs.com/careers","https://www.pacificlife.com/careers.html"]),
 (241,"Auto-Owners Insurance",["autoowners"],["https://careers.auto-owners.com/"]),
 (242,"Peter Kiewit Sons'",["kiewit"],["https://www.kiewitjobs.com/"]),
 (243,"Lincoln National",["lincolnfinancial","lfg"],["https://careers.lincolnfinancial.com/"]),
 (244,"Steel Dynamics",["steeldynamics","sdi"],["https://www.steeldynamics.com/careers/"]),
 (245,"Emerson Electric",["emerson"],["https://hdjq.fa.us2.oraclecloud.com","https://www.emerson.com/en-us/careers"]),
 (246,"Asbury Automotive Group",["asbury"],["https://careers.asburyauto.com/"]),
 (247,"ManpowerGroup",["manpowergroup","manpower"],["https://www.manpowergroup.com/en/careers"]),
 (248,"W.W. Grainger",["grainger"],["https://jobs.grainger.com/"]),
 (249,"Jones Financial (Edward Jones)",["edwardjones"],["https://careers.edwardjones.com/"]),
 (250,"O'Reilly Automotive",["oreilly","oreillyauto"],["https://corporate.oreillyauto.com/careers"]),
 (251,"Vistra",["vistra","vistraenergy"],["https://careers.vistracorp.com/"]),
 (252,"Texas Instruments",["ti","texasinstruments"],["https://careers.ti.com/"]),
 (253,"MGM Resorts International",["mgmresorts","mgm"],["https://careers.mgmresorts.com/"]),
 (254,"Corteva",["corteva"],["https://careers.corteva.com/"]),
 (255,"Universal Health Services",["uhs","uhsinc"],["https://uhs.wd5.myworkdayjobs.com/UHS","https://jobs.uhsinc.com/"]),
 (256,"PulteGroup",["pultegroup","pulte"],["https://careers.pultegroup.com/"]),
 (257,"Omnicom Group",["omnicom","omc"],["https://www.omnicomgroup.com/careers/"]),
 (258,"Dick's Sporting Goods",["dicks","dsg"],["https://dsg.wd1.myworkdayjobs.com/dsg_careers","https://www.dickssportinggoods.jobs/"]),
 (259,"Devon Energy",["devonenergy","devon"],["https://careers.devonenergy.com/"]),
 (260,"Leidos Holdings",["leidos"],["https://careers.leidos.com/"]),
 (261,"Aflac",["aflac"],["https://careers.aflac.com/"]),
 (262,"Targa Resources",["targa","targaresources"],["https://careers.targaresources.com/"]),
 (263,"Murphy USA",["murphyusa"],["https://careers.murphyusa.com/"]),
 (264,"LPL Financial Holdings",["lpl","lplfinancial"],["https://careers.lpl.com/"]),
 (265,"EMCOR Group",["emcor"],["https://careers.emcorgroup.com/"]),
 (266,"Kinder Morgan",["kindermorgan","kmi"],["https://careers.kindermorgan.com/"]),
 (267,"Consolidated Edison",["coned","conedison"],["https://careers.coned.com/"]),
 (268,"Keurig Dr Pepper",["keurigdrpepper","kdp"],["https://careers.keurigdrpepper.com/"]),
 (269,"Republic Services",["republicservices"],["https://jobs.republicservices.com/"]),
 (270,"Markel Group",["markelcorp","markel"],["https://markelcorp.wd5.myworkdayjobs.com/GlobalCareers"]),
 (271,"Farmers Insurance Exchange",["farmers","farmersinsurance"],["https://www.farmers.com/careers/"]),
 (272,"Dominion Energy",["dominionenergy","dominion"],["https://careers.dominionenergy.com/"]),
 (273,"Land O'Lakes",["landolakes"],["https://landolakes.wd1.myworkdayjobs.com/LandOLakes"]),
 (274,"IQVIA Holdings",["iqvia"],["https://iqvia.wd1.myworkdayjobs.com/IQVIA","https://jobs.iqvia.com/"]),
 (275,"Fox",["fox","foxcorp"],["https://careers.foxcorporation.com/"]),
 (276,"AECOM",["aecom"],["https://aecom.jobs/"]),
 (277,"C.H. Robinson Worldwide",["chrobinson","chrw"],["https://jobs.chrobinson.com/"]),
 (278,"Bitgo Holdings",["bitgo"],["https://www.bitgo.com/careers/"]),
 (279,"United Rentals",["unitedrentals","ur"],["https://careers.unitedrentals.com/"]),
 (280,"Ecolab",["ecolab"],["https://ecolab.wd1.myworkdayjobs.com/Ecolab_Careers","https://jobs.ecolab.com/"]),
 (281,"Illinois Tool Works",["itw"],["https://careers.itw.com/"]),
 (282,"Casey's General Stores",["caseys"],["https://www.caseys.com/careers"]),
 (283,"Raymond James Financial",["raymondjames","rjf"],["https://www.raymondjames.com/careers"]),
 (284,"PPG Industries",["ppg"],["https://ppg.wd5.myworkdayjobs.com/PPG_Careers","https://www.ppg.com/en-US/careers"]),
 (285,"DTE Energy",["dte","dteenergy"],["https://dte.wd1.myworkdayjobs.com/DTE_Careers","https://www.dteenergy.com/careers"]),
 (286,"Corning",["corning"],["https://corning.wd1.myworkdayjobs.com/corning_careers","https://www.corning.com/careers"]),
 (287,"Principal Financial",["principal","principalfinancial"],["https://careers.principal.com/"]),
 (288,"Mutual of Omaha",["mutualofomaha"],["https://careers.mutualofomaha.com/"]),
 (289,"Kohl's",["kohls"],["https://careers.kohls.com/"]),
 (290,"Tractor Supply",["tractorsupply","tsc"],["https://careers.tractorsupply.com/"]),
 (291,"Whirlpool",["whirlpool"],["https://whirlpool.wd5.myworkdayjobs.com/whirlpool_jobs","https://www.whirlpoolcareers.com/"]),
 (292,"Fluor",["fluor"],["https://fluor.wd1.myworkdayjobs.com/fluor_careers","https://www.fluor.com/careers"]),
 (293,"Gap",["gap","gapinc"],["https://www.gapinc.com/en-us/careers"]),
 (294,"S&P Global",["spglobal"],["https://spgi.wd5.myworkdayjobs.com/SPGI_Careers","https://careers.spglobal.com/"]),
 (295,"Ally Financial",["ally","allyfinancial"],["https://www.ally.com/careers/"]),
 (296,"Builders FirstSource",["bldr","buildersfirstsource"],["https://careers.bldr.com/"]),
 (297,"Sonic Automotive",["sonicautomotive","sonic"],["https://careers.sonicautomotive.com/"]),
 (298,"Stanley Black & Decker",["sbd","stanleyblackanddecker"],["https://sbd.wd1.myworkdayjobs.com/SBD","https://www.stanleyblackanddecker.com/careers"]),
 (299,"Kenvue",["kenvue"],["https://kenvue.wd1.myworkdayjobs.com/Kenvue","https://www.kenvue.com/careers"]),
 (300,"Kyndryl Holdings",["kyndryl"],["https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers"]),
]
